export const mockContactsData = [
  {
    recordID: '1',
    givenName: 'John',
    familyName: 'Doe',
    phoneNumbers: [{ number: '123456789', label: 'mobile' }],
    emailAddresses: [{ email: 'test@gmail.com', label: 'work' }],
    hasThumbnail: false,
    thumbnailPath: 'test.jpg',
    backTitle: '',
    company: null,
    displayName: '',
    middleName: '',
    jobTitle: '',
    isStarred: false,
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {
      day: 1,
      month: 1,
      year: 2000,
    },
    imAddresses: [],
    urlAddresses: [],
    note: '',
  },
];
