export const mockContactDetailData = [
  {
    recordID: '1',
    backTitle: '',
    company: null,
    emailAddresses: [{ email: 'test@gmail.com', label: 'work' }],
    displayName: 'Annie Doe',
    familyName: 'Doe',
    givenName: 'Annie',
    middleName: '',
    jobTitle: '',
    phoneNumbers: [{ number: '123456789', label: 'mobile' }],
    hasThumbnail: false,
    thumbnailPath: 'test.jpg',
    isStarred: true,
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {
      day: 1,
      month: 1,
      year: 2000,
    },
    imAddresses: [],
    urlAddresses: [],
    note: 'Some note about the contact',
  },
];

export const mockContactWithMultipleDetails = [
  {
    recordID: '2',
    backTitle: '',
    company: 'Company XYZ',
    emailAddresses: [
      { email: 'bob@example.com', label: 'personal' },
      { email: 'bob.work@example.com', label: 'work' },
    ],
    displayName: 'Bob Marley',
    familyName: 'Marley',
    givenName: 'Bob',
    middleName: '',
    jobTitle: 'Software Engineer',
    phoneNumbers: [
      { number: '987654321', label: 'home' },
      { number: '555555555', label: 'work' },
    ],
    hasThumbnail: false,
    thumbnailPath: 'test.jpg',
    isStarred: false,
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {
      day: 1,
      month: 1,
      year: 1980,
    },
    imAddresses: [],
    urlAddresses: [],
    note: 'Some note about Bob Marley',
  },
];
