export const mockContactsSingleFavoriteData = [
  {
    recordID: '1',
    givenName: 'Annie',
    familyName: 'Doe',
    phoneNumbers: [{ number: '123456789', label: 'mobile' }],
    emailAddresses: [{ email: 'test@gmail.com', label: 'work' }],
    hasThumbnail: false,
    thumbnailPath: 'test.jpg',
    backTitle: '',
    company: null,
    displayName: '',
    middleName: '',
    jobTitle: '',
    isStarred: true,
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {
      day: 1,
      month: 1,
      year: 2000,
    },
    imAddresses: [],
    urlAddresses: [],
    note: '',
  },
  {
    recordID: '2',
    givenName: 'Bob',
    familyName: 'Marley',
    phoneNumbers: [{ number: '34434343', label: 'mobile' }],
    emailAddresses: [{ email: 'yuhuu@gmail.com', label: 'work' }],
    hasThumbnail: false,
    thumbnailPath: 'test.jpg',
    backTitle: '',
    company: null,
    displayName: '',
    middleName: '',
    jobTitle: '',
    isStarred: false,
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {
      day: 1,
      month: 1,
      year: 2000,
    },
    imAddresses: [],
    urlAddresses: [],
    note: '',
  },
  {
    recordID: '3',
    givenName: 'Carol',
    familyName: 'Denver',
    phoneNumbers: [{ number: '34434343', label: 'mobile' }],
    emailAddresses: [{ email: 'yuhuu@gmail.com', label: 'work' }],
    hasThumbnail: false,
    thumbnailPath: 'test.jpg',
    backTitle: '',
    company: null,
    displayName: '',
    middleName: '',
    jobTitle: '',
    isStarred: false,
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {
      day: 1,
      month: 1,
      year: 2000,
    },
    imAddresses: [],
    urlAddresses: [],
    note: '',
  },
];

export const mockContactsNoFavoriteData = [
  {
    recordID: '2',
    givenName: 'Bob',
    familyName: 'Marley',
    phoneNumbers: [{ number: '34434343', label: 'mobile' }],
    emailAddresses: [{ email: 'yuhuu@gmail.com', label: 'work' }],
    hasThumbnail: false,
    thumbnailPath: 'test.jpg',
    backTitle: '',
    company: null,
    displayName: '',
    middleName: '',
    jobTitle: '',
    isStarred: false,
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {
      day: 1,
      month: 1,
      year: 2000,
    },
    imAddresses: [],
    urlAddresses: [],
    note: '',
  },
  {
    recordID: '3',
    givenName: 'Carol',
    familyName: 'Denver',
    phoneNumbers: [{ number: '34434343', label: 'mobile' }],
    emailAddresses: [{ email: 'yuhuu@gmail.com', label: 'work' }],
    hasThumbnail: false,
    thumbnailPath: 'test.jpg',
    backTitle: '',
    company: null,
    displayName: '',
    middleName: '',
    jobTitle: '',
    isStarred: false,
    postalAddresses: [],
    prefix: '',
    suffix: '',
    department: '',
    birthday: {
      day: 1,
      month: 1,
      year: 2000,
    },
    imAddresses: [],
    urlAddresses: [],
    note: '',
  },
];
